package io.github.duckasteroid.agentdocs.publish.validation;

import org.gradle.api.GradleException;

/**
 * Warns when publisher-provided {@code name} is present because resolver naming is authoritative.
 */
public final class SkillNameRule implements AgentDocsValidationRule {
    @Override
    public String id() {
        return "skill-name";
    }

    @Override
    public ValidationResult validate(ValidationContext context) {
        try {
            String name = SkillValidationSupport.parseFrontmatter(context).name();
            if (name == null || name.isBlank()) {
                return ValidationResult.pass(id());
            }
            return ValidationResult.warn(id(),
                    "Publisher-provided SKILL.md frontmatter 'name' is ignored; "
                            + "name is generated by plugin.");
        } catch (GradleException exception) {
            return ValidationResult.error(id(), exception.getMessage());
        }
    }
}
